name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: aws-actions/amazon-ecr-build-push@v2
        with:
          repository: ecr-repo
          region: ap-south-1
          image-tags: |
           latest
           ${{ github.sha }}


      - name: Deploy to ECS
        run: |
         aws ecs update-service \
         --cluster node-cluster-app \
         --service my-task-service \
          --force-new-deployment

